language: node_js
sudo: false
node_js:
- 10
install:
- npm i
- npm i codecov -g
script:
- npm run coverage
- codecov
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: coTG3YTkzurOkpXAD3zPelXbX9ZBuv40jM/agQ2f3M9JVnzbnKJ0aK+rA/z6RxotSJ6P+pAPkmBOb+d3oYeWMjDJD7mGl6qsOWYJVzn5QU8EXrjfQqTjqSIUt6V3UdcXg2vOqdwMlcZTjuylC4IbRMEMMk0UYaOK134qkpxbsqpVTtpdnwi0ije71ip7LZBtlarT7TzIrc1pcZ0DZY+h/4aUf3Zd7KVDq2HmuCZxVJCPR23Nn/HJKj4UJTR2KnS+xqbQejauwL/SCHioN5Oyo6Hk+/IFGxKDzpxFm/XP1H7Hr2sshlglCP4uIHFGOaKg3VI02ced2DgtaPkN1RN04W9xG+8EkyR7Ki9RLf8acKgvBzRQ4MaikaypaiC9l/uURyqN6UdjZab9BNedbzvZFjj6AktKt5YJmatXFMEuWvSce7PFsWVB+cO8QXpVo8SD7Vh/34Tv6gyFn4MJ38lhQtuUV9lwouciqt0PEXVRYx6BOEL7aqCWcHfMBzM4dPANdZG3GLcSFihn62pmubuNYtStkljTZaTjlpRCFIT+ZZi9OthPPRoKNF8oUe+MB0hzrVDhef/Qh0pNMS6aPeK2i5FUqBF4sUfiSHobTnKQvvdPw57UoAuTufv6DkXxhJTCYgagRuYqJi0pErSBzRiSxbzcAjMjgnSXCGt/WLDjVNs=
