language: node_js
sudo: false
node_js:
- 10
install:
- npm i
- npm i codecov -g
script:
- npm run coverage
- codecov
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: h7lpE66zAy4pNaD3S913hSdIS74Olp2lPAlzWJ8WSmu68gHAXB3l+UUns5BI2nxT1JJjnhmGwLtkWvytBJegfdEfM9ec4XR5wcdcpDFdP/zzX+5v1rZOnpj164WZltRpPVarE8DmSBAVS2dHPN4Ci8KzMn0VZgWKvW2vwq55+ggt4D51Fg/AnlWdEx+s2OlRN5x+gJPPry0ssz6/CHF1RmYTVZDr57qmX7d5N+3KlJgwGNOqs6zvuj2tzfXiTRlDoBr54dbSw7WGhsOpomW7SwzLrtRzUaQd1PgTLsmJJNO2NNYcbFC7AC7tiRs93Hh57oTHo0lgFawz2BDL+CVBUqrk7qwJt8n6bioMXNiVdewTfwQ+815pRONWXiFr11koUj0De8KSNhPmstJCQQmHGBEbqnrqVzD83ihsqmnNNdSIB6GRstTg8SjBIWRAATk4h2Un//ptyYGCu9W8pIt/GVehoB3qI39iquwJaqABglkraWa/yMYp7gZ2p/nMm1cxj5x7h4OXrtMiAwjA9u3ltud++CHUBGYG6qES8tLo+VLjH7h+xiFIulwQS2i0RiVsFO1Nvze7KDXo4Bfm8IsuRRo5naQLcKouYnjGi3gRf+cyMOqI9gCOlGYAWXCbiJ4hMhvzrAYIR7Ehqa35mEYDqWSuRtAGF/CiRv4JBCEAd70=
