#import "../fragments/MediaFields.gql"

  query Media(
    $isAdult: Boolean
    $id: Int
    $format: ScoreFormat
  ) {
    Media(
      isAdult: $isAdult
      id: $id
    ) {
      ...MediaFields
    }
  }