fragment ToggleFavourite_media on Media{
    id
    favourites
    isFavourite
    type
}

query ToggleFavouriteQuery($id: Int) {
  Media(id: $id) {
    id
    isFavourite
    favourites
  }
}

mutation ToggleFavouriteMutation(
  $animeId: Int
  $mangaId: Int
) {
  ToggleFavourite(
    animeId: $animeId
    mangaId: $mangaId
  ) {
    anime {
      pageInfo {
        hasNextPage
      }
    }
    manga {
      pageInfo {
        hasNextPage
      }
    }
  }
}
