#import '../components/TheTimeline.gql'

query SearchPageQuery(
  $isAdult: Boolean
  $search: String
  $idIn: [Int]
  $page: Int = 0
  $includedTags: [String]
  $onList: Boolean
  $year: Int
  $type: MediaType
  $status: [MediaStatus]
  $season: MediaSeason
  $sort: [MediaSort]
  $perPage: Int = 50
) {
  Page(page: $page, perPage: $perPage) {
    pageInfo {
      currentPage
      hasNextPage
    }
    media(
      isAdult: $isAdult
      search: $search
      id_in: $idIn
      tag_in: $includedTags
      onList: $onList
      seasonYear: $year
      season: $season
      type: $type
      sort: $sort
      status_in: $status
    ) {
      ...TheTimeline_media
    }
  }
}

query SearchViewerQuery {
  Viewer {
    id
    options {
      displayAdultContent
    }
  }
}
