#import '../components/MediaEdit.gql'
#import '../hooks/ToggleFavourite.gql'
#import '../hooks/Share.gql'

fragment TimelineDrawer_media on Media {
  id
  siteUrl
  ...ToggleFavourite_media
  ...Share_media
  ...MediaEdit_media
}
