#import './MediaCardItemAvatar'
#import './MediaCardItemSubtitle'
#import './MediaCardItemTitle'

fragment ChangeCardBanner_media on Media {
  id
  title {
    userPreferred
  }
  ...MediaCardItemAvatar_media
  ...MediaCardItemSubtitle_media
  ...MediaCardItemTitle_media
}
