#import './MediaEdit.gql'
#import '../hooks/ToggleFavourite.gql'
#import '../hooks/Share.gql'

fragment MediaCardActions_media on Media {
  id
  type
  siteUrl
  ...ToggleFavourite_media
  ...Share_media
  ...MediaEdit_media
}


