<template>
  <v-navigation-drawer
    right
    floating
    mini-variant
    permanent
    app
    mini-variant-width="72"
    color="transparent"
  >
    <slot></slot>
  </v-navigation-drawer>
</template>
