#import "./FuzzyDateFields.gql"
  fragment MediaListFields on MediaList {
    id
    mediaId
    status
    score(format: $format)
    progress
    progressVolumes
    repeat
    private
    notes
    advancedScores
    startedAt {
...FuzzyDateFields
    }
    completedAt {
...FuzzyDateFields
    }
  }