#import './views/TimelineAppBar.gql'
#import './views/TimelineDrawer.gql'

query RouterTimelineAppBarQuery($id: Int) {
  Media(id: $id) {
    id
    ...TimelineAppBar_media
  }
}

query RouterTimelineDrawerQuery($id: Int) {
  Media(id: $id) {
    id
    ...TimelineDrawer_media
  }
}


query RouterTimelineQuery($id: Int) {
  Media(id: $id) {
    id
    title {
      userPreferred
    }
  }
}
