#import "../fragments/MediaFields.gql"
#import "../fragments/PageInfoFields.gql"

query Page(
  $isAdult: Boolean
  $search: String
  $idIn: [Int]
  $page: Int = 0
  $includedTags: [String]
  $onList: Boolean
  $year: Int
  $type: MediaType
  $status: [MediaStatus]
  $season: MediaSeason
  $sort: [MediaSort]
  $format: ScoreFormat
  $perPage: Int = 50
) {
  Page(page: $page, perPage: $perPage) {
    pageInfo {
      ...PageInfoFields
    }
    media(
      isAdult: $isAdult
      search: $search
      id_in: $idIn
      tag_in: $includedTags
      onList: $onList
      seasonYear: $year
      season: $season
      type: $type
      sort: $sort
      status_in: $status
    ) {
      ...MediaFields
    }
  }
}
